[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore = ["I001"]

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "single"
# 缩进使用1个Tab替换4个空格
# indent-style = "tab"